"""
Independent checks on the inheritance module.

Each fixture targets a SPECIFIC way this module gets built wrong. The expected values are
derived from the Code and the regs, cited inline, on 2026-08-21 — not from any implementation.

Same rule as Phase 0: nothing here may import from src/. If the module and these fixtures
ever share code, the checks are worthless.
"""
import json, os

ROOT = os.path.join(os.path.dirname(__file__), "..", "fixtures", "inheritance")
os.makedirs(ROOT, exist_ok=True)
INDEX = []

C1014   = "IRC 1014 — https://www.law.cornell.edu/uscode/text/26/1014"
C1014c  = "IRC 1014(c) (IRD excluded from step-up)"
C1014b6 = "IRC 1014(b)(6) (community property double step-up)"
C1014f  = "IRC 1014(f) / IRC 6035 (basis consistency, Form 8971)"
C1223   = "IRC 1223(9) — https://www.law.cornell.edu/uscode/text/26/1223"
C2032   = "IRC 2032 (alternate valuation) — https://www.law.cornell.edu/uscode/text/26/2032"
C691c   = "IRC 691(c) (deduction for estate tax on IRD)"
R9_5    = "Treas. Reg. 1.401(a)(9)-5(e)"
R9_4    = "Treas. Reg. 1.401(a)(9)-4 (Sept 30 determination date)"
R9_8    = "Treas. Reg. 1.401(a)(9)-8 (separate accounts)"
R9_3d   = "Treas. Reg. 1.401(a)(9)-3(d) (SECURE 2.0 sec. 327 spousal election)"
R4974   = "Treas. Reg. 54.4974-1(g)(3) (automatic excise waiver)"
R1250   = "Treas. Reg. 1.1250-3(b) (transfer at death)"
P555    = "IRS Pub 555 / IRM 25.18.1 (community property)"
TRUSTBR = "IRC 1(e); rules/federal/estates-trusts-2026.json"


def emit(fid, title, catches, inp, expected, authority, notes=""):
    doc = {
        "id": fid, "title": title, "module": "inheritance", "tax_year": 2026,
        "catches": catches, "authority": authority,
        "input": inp, "expected": expected, "notes": notes,
        "oracle": "derived from statute/regulation on 2026-08-21; NOT generated by src/",
    }
    with open(os.path.join(ROOT, fid + ".json"), "w") as f:
        json.dump(doc, f, indent=2)
    INDEX.append({"id": fid, "title": title, "catches": catches})


# ---------------------------------------------------------------- basis / step-up

emit("INH-01", "Inherited land — FMV known, basis NOT verified",
     "The headline guardrail: FMV silently copied into taxBasis.",
     {"assetType": "land", "decedentName": "SPECIMEN", "dateOfDeath": "2026-03-14",
      "dateOfDeathFMV": {"state": "verified", "value": 310000,
                         "provenance": {"sourceType": "appraisal", "asOfDate": "2026-05-02"}},
      "taxBasis": {"state": "unknown", "value": None},
      "appraisalStatus": "obtained"},
     {"stepUpRegime": "section_1014",
      "dateOfDeathFMV": 310000,
      "taxBasis": None, "taxBasisState": "unknown", "basisStatus": "unknown",
      "flags": ["FLAG_FMV_KNOWN_BASIS_NOT_VERIFIED"],
      "caseStatus": "basis_missing",
      "renderedBasis": "—",
      "mustNotEqual": {"taxBasis": 310000}},
     [C1014],
     "If taxBasis comes back 310000 the module copied FMV into basis. That is the single "
     "failure this whole module exists to prevent. Render must show an em dash, never the FMV.")

emit("INH-02", "Inherited TRADITIONAL IRA — no step-up exists at all",
     "A basis step-up applied to income in respect of a decedent.",
     {"assetType": "traditional_ira", "decedentName": "SPECIMEN", "dateOfDeath": "2026-03-14",
      "accountValueAtDeath": {"state": "verified", "value": 425000,
                              "provenance": {"sourceType": "custodian_verified",
                                             "documentStatus": "tax_form_issued",
                                             "asOfDate": "2026-03-14"}},
      "decedentForm8606Basis": {"state": "unknown", "value": None},
      "federalEstateTaxPaidOnIRD": {"state": "verified", "value": 0}},
     {"stepUpRegime": "ird_no_stepup",
      "valueAtDeath": 425000,
      "taxBasisFieldPresent": False,
      "decedentAfterTaxBasis": None, "decedentAfterTaxBasisState": "unknown",
      "possibleIRD": True,
      "section691cDeductionAvailable": False,
      "distributionCharacter": "ordinary_income",
      "flags": ["FLAG_IRD_NO_STEPUP", "FLAG_BASIS_UNKNOWN"],
      "caseStatus": "cpa_review_required"},
     [C1014c, C691c],
     "READ THIS ONE BY HAND. IRC 1014(c): section 1014 does not apply to IRD. There is no "
     "partial step-up, no step-up requiring verification — none. The IRD branch of BasisModel "
     "must have NO taxBasis field, so that copying value-at-death into basis is a COMPILE "
     "ERROR. $425,000 is a reporting figure and an estate value. It is not basis and can "
     "never become basis.")

emit("INH-03", "Inherited stock sold 4 months after death",
     "Holding period computed from the beneficiary's actual holding period.",
     {"assetType": "publicly_traded_stock", "dateOfDeath": "2026-03-14",
      "dateReceived": "2026-04-20", "dateSold": "2026-07-18",
      "dateOfDeathFMV": {"state": "verified", "value": 82400,
                         "provenance": {"sourceType": "custodian_verified",
                                        "documentStatus": "tax_form_issued",
                                        "asOfDate": "2026-03-14"}},
      "taxBasis": {"state": "verified", "value": 82400,
                   "provenance": {"sourceType": "custodian_verified",
                                  "documentStatus": "tax_form_issued", "asOfDate": "2026-04-20"}},
      "saleProceeds": {"state": "verified", "value": 91200}},
     {"stepUpRegime": "section_1014",
      "holdingPeriodTreatment": "long_term",
      "holdingPeriodRuleId": "IRC_1223_9",
      "realizedGainLoss": 8800,
      "flags": ["FLAG_INHERITED_PROPERTY_SOLD"]},
     [C1223, C1014],
     "Held four months, but long-term. IRC 1223(9) applies because basis was determined under "
     "1014 AND the sale was within one year of death. Note the real shape of the rule: it is a "
     "RESCUE provision for dispositions inside one year. Past a year the holding period is long "
     "naturally. Here basis IS custodian-verified, so a gain may be computed - contrast INH-01.")

emit("INH-04", "Inherited IRA distribution is ordinary income, not capital gain",
     "IRC 1223(9) long-term treatment wrongly extended to IRD.",
     {"assetType": "inherited_traditional_ira", "dateOfDeath": "2026-03-14",
      "grossDistribution": {"state": "verified", "value": 45000,
                            "provenance": {"sourceType": "custodian_verified",
                                           "documentStatus": "tax_form_issued",
                                           "asOfDate": "2026-12-31"}}},
     {"distributionCharacter": "ordinary_income",
      "holdingPeriodTreatment": "not_applicable",
      "section1223_9Applies": False,
      "reason": "IRC 1223(9) requires basis determined under section 1014; 1014(c) excludes IRD."},
     [C1223, C1014c],
     "The 1223(9) rescue cannot reach IRD because 1014 never applied. If the module reports "
     "long-term capital gain on an inherited IRA distribution it has chained the two rules "
     "without checking the precondition.")

emit("INH-05", "Community property, Texas — FULL double step-up",
     "Only the decedent's half stepped up in a community property state.",
     {"assetType": "taxable_brokerage", "decedentDomicileState": "TX",
      "dateOfDeath": "2026-03-14", "propertyCharacter": "community_property",
      "totalDateOfDeathFMV": {"state": "verified", "value": 600000},
      "originalJointCostBasis": {"state": "verified", "value": 200000}},
     {"communityPropertyTreatment": "full_double_stepup",
      "portionReceivingAdjustment": 1.0,
      "adjustedBasisIfVerified": 600000,
      "flags": ["FLAG_COMMUNITY_PROPERTY_DOUBLE_STEPUP"]},
     [C1014b6, P555],
     "BOTH halves adjust. A module that steps up only the decedent's half reports $400,000 of "
     "basis instead of $600,000 - a $200,000 phantom gain on a later sale. Nine mandatory "
     "states plus PR and Guam: AZ CA ID LA NV NM TX WA WI.")

emit("INH-06", "Elective community property trust state — UNSETTLED, do not model",
     "Auto-applying the double step-up in an opt-in CP trust state.",
     {"assetType": "taxable_brokerage", "decedentDomicileState": "TN",
      "dateOfDeath": "2026-03-14", "propertyCharacter": "elective_community_property_trust",
      "totalDateOfDeathFMV": {"state": "verified", "value": 600000}},
     {"communityPropertyTreatment": "elective_regime_unsettled",
      "portionReceivingAdjustment": None,
      "adjustedBasisIfVerified": None,
      "flags": ["FLAG_ELECTIVE_CP_REGIME_UNSETTLED"],
      "caseStatus": "attorney_review_required"},
     [P555, C1014b6],
     "AK, SD, TN, FL, KY allow elective community property trusts. IRS Pub 555 expressly "
     "disclaims coverage and IRM 25.18.1 cites Commissioner v. Harmon against elective regimes "
     "in the income-reporting context. There is no published IRS position on 1014(b)(6) here. "
     "Per CLAUDE.md rule 4: do not synthesize a treatment. Flag and stop.")

emit("INH-07", "Alternate valuation date is an ESTATE-level election",
     "AVD modeled as a free per-asset field.",
     {"estate": {"form706Filed": True, "alternateValuationElected": True,
                 "electionDecreasesGrossEstateAndTax": True,
                 "dateOfDeath": "2026-03-14"},
      "assets": [{"assetType": "land", "disposedBeforeAVD": False},
                 {"assetType": "publicly_traded_stock", "disposedBeforeAVD": True,
                  "dispositionDate": "2026-06-02"}]},
     {"electionScope": "entire_estate",
      "electionIrrevocable": True,
      "alternateValuationDateDefault": "2026-09-14",
      "assetValuationDates": ["2026-09-14", "2026-06-02"],
      "flags": ["FLAG_ALTERNATE_VALUATION_ELECTED", "FLAG_FORM_8971_EXPECTED"],
      "perAssetElectionPermitted": False},
     [C2032, C1014f],
     "Six months after death, or date of disposition if earlier. All-or-nothing for the whole "
     "estate, irrevocable, and allowed only if it decreases BOTH the gross estate and the sum "
     "of estate plus GST tax. With a $15,000,000 exclusion in 2026 almost no estate files a 706 "
     "at all, so AVD data being present is itself worth confirming.")

# ---------------------------------------------------------------- retirement timing

emit("INH-08", "10-year rule end date — the off-by-one",
     "tenYearRuleEndDate computed as 10 years from the DATE of death.",
     {"assetType": "inherited_traditional_ira", "dateOfDeath": "2026-03-14",
      "beneficiaryClassification": "noneligible_designated_beneficiary",
      "decedentRBDStatus": "after_required_beginning_date"},
     {"tenYearRuleEndDate": "2036-12-31",
      "wrongAnswerToWatchFor": "2036-03-14",
      "annualRmdsRequiredYears1Through9": True,
      "flags": ["FLAG_TEN_YEAR_RULE"]},
     [R9_5],
     "December 31 of the 10th calendar year FOLLOWING the year of death. Reg. 1.401(a)(9)-5(e)(2). "
     "Death on/after the RBD also means annual RMDs in years 1-9 IN ADDITION to the year-10 "
     "payout - the at-least-as-rapidly rule and the 10-year rule both apply.")

emit("INH-09", "Minor child EDB — clock starts at 21",
     "10-year clock started at the date of death for a minor child of the owner.",
     {"assetType": "inherited_traditional_ira", "dateOfDeath": "2026-03-14",
      "beneficiaryClassification": "eligible_designated_beneficiary",
      "edbSubtype": "minor_child_of_owner", "beneficiaryDateOfBirth": "2015-06-01"},
     {"lifeExpectancyPaymentsUntilYear": 2036,
      "ageOfMajorityAttainedYear": 2036,
      "finalDistributionDeadline": "2046-12-31",
      "flags": ["FLAG_MINOR_CHILD_EDB", "FLAG_TEN_YEAR_RULE"]},
     [R9_5],
     "Child turns 21 in 2036, 31 in 2046. Annual life-expectancy payments until 21, then full "
     "payout by Dec 31 of the year the child turns 31. CHILD OF THE OWNER ONLY - a grandchild "
     "or niece is not an EDB under this rule.")

emit("INH-10", "Successor beneficiary with unknown original facts",
     "A fresh 10-year window granted to a successor beneficiary.",
     {"assetType": "inherited_traditional_ira", "dateOfDeath": "2026-03-14",
      "isSuccessorBeneficiary": True,
      "originalDecedentName": {"state": "unknown", "value": None},
      "originalDateOfDeath": {"state": "unknown", "value": None},
      "originalBeneficiaryRegime": {"state": "unknown", "value": None}},
     {"tenYearRuleEndDate": None,
      "scheduledeterminable": False,
      "flags": ["FLAG_SUCCESSOR_BENEFICIARY"],
      "caseStatus": "cpa_review_required",
      "requiredMessage": "Inherited retirement distribution schedule cannot be determined from available data."},
     [R9_5],
     "A successor generally steps into the REMAINDER of the original window, not a new one. "
     "With the original facts unknown, no date can be computed. The module must refuse rather "
     "than default to 2036-12-31.")

emit("INH-11", "Year-of-death RMD where death PRECEDED the RBD",
     "Reporting 'not_satisfied' when no year-of-death RMD was ever due.",
     {"assetType": "inherited_traditional_ira", "dateOfDeath": "2026-03-14",
      "decedentBirthYear": 1958, "decedentRBDStatus": "before_required_beginning_date",
      "amountTakenBeforeDeath": {"state": "verified", "value": 0}},
     {"decedentYearOfDeathRMDRequired": False,
      "status": "not_applicable",
      "amountRequired": None,
      "flags": [],
      "mustNotReport": "not_satisfied"},
     [R9_5],
     "No year-of-death RMD exists unless the owner died on or after the RBD. decedentRBDStatus "
     "gates the entire subsection. Reporting 'not_satisfied' here invents a deficiency and will "
     "alarm a client for no reason.")

emit("INH-12", "Year-of-death RMD unsatisfied — but the excise waiver is automatic",
     "Alarmist wording on a situation with an automatic statutory cure.",
     {"assetType": "inherited_traditional_ira", "dateOfDeath": "2026-09-02",
      "decedentBirthYear": 1950, "decedentRBDStatus": "after_required_beginning_date",
      "amountRequired": {"state": "verified", "value": 38000},
      "amountTakenBeforeDeath": {"state": "verified", "value": 12000},
      "beneficiaryCompletedRemainingRMD": {"state": "verified", "value": False}},
     {"amountRemaining": 26000,
      "status": "partially_satisfied",
      "statutoryDeadline": "2026-12-31",
      "automaticExciseWaiverAvailable": True,
      "waiverDeadlineDescription": "beneficiary's tax filing deadline including extensions, or the last day of the following calendar year if later",
      "form5329WaiverRequestRequired": False,
      "flags": ["FLAG_YEAR_OF_DEATH_RMD_UNKNOWN"]},
     [R4974],
     "Reg. 54.4974-1(g)(3) waives the excise tax automatically if the beneficiary takes the "
     "corrective distribution in time. No Form 5329 request needed. Word the flag as "
     "coordination, not as a penalty notice.")

emit("INH-13", "Separate accounts not yet established — deadline still open",
     "A purely retrospective module missing a live, time-critical deadline.",
     {"assetType": "inherited_traditional_ira", "dateOfDeath": "2026-03-14",
      "multipleBeneficiaries": True, "beneficiaryCount": 3,
      "separateAccountsEstablished": {"state": "verified", "value": False},
      "packetGenerationDate": "2027-02-10"},
     {"septemberThirtyDeterminationDate": "2027-09-30",
      "separateAccountDeadline": "2027-12-31",
      "deadlineStillOpenAtGeneration": True,
      "consequenceIfMissed": "Section 401(a)(9) applies to the aggregate account; in practice the least favorable beneficiary's rules apply to all.",
      "flags": ["FLAG_SEPARATE_ACCOUNTS_DEADLINE_OPEN", "FLAG_SEPT_30_DETERMINATION_DATE_OPEN"],
      "caseStatus": "cpa_review_required"},
     [R9_4, R9_8],
     "Two distinct sequential dates: Sept 30 of the year after death identifies the designated "
     "beneficiaries (disclaimers and cash-outs through that date can remove a charity or estate "
     "and preserve DB status); Dec 31 of the year after death is the separate-accounting "
     "deadline. This is the one place the module should look FORWARD - a February packet that "
     "names an open deadline does something a year-end summary normally cannot.")

emit("INH-14", "Accumulation trust as beneficiary — compressed brackets",
     "Treating a trust beneficiary as if taxed at individual rates.",
     {"assetType": "inherited_traditional_ira", "dateOfDeath": "2026-03-14",
      "beneficiaryClassification": "trust", "trustType": "accumulation",
      "grossDistribution": {"state": "verified", "value": 60000},
      "distributedToIndividualBeneficiary": {"state": "verified", "value": 0}},
     {"trustType": "accumulation",
      "retainedIncomeSubjectToTrustBrackets": True,
      "trustTopBracketThreshold2026": 16000,
      "trustTopRate": 0.37,
      "flags": ["FLAG_ACCUMULATION_TRUST_COMPRESSED_BRACKETS", "FLAG_K1_EXPECTED"],
      "mustNotCompute": "trust tax liability or DNI allocation"},
     [TRUSTBR],
     "A trust reaches 37% at roughly $16,000 of retained taxable income versus about $768,700 "
     "for MFJ. A conduit trust passes distributions through to the individual; an accumulation "
     "trust does not. Name the exposure; do not compute the trust's tax.")

# ---------------------------------------------------------------- property / integration

emit("INH-15", "Inherited rental — depreciation RESTARTS, decedent's does not carry over",
     "The requirements document's own flag wording, which is misleading here.",
     {"assetType": "rental_property", "dateOfDeath": "2026-03-14",
      "dateOfDeathFMV": {"state": "verified", "value": 480000,
                         "provenance": {"sourceType": "appraisal", "asOfDate": "2026-05-10"}},
      "decedentAccumulatedDepreciation": {"state": "verified", "value": 210000},
      "heirTookDepreciationBeforeDeath": {"state": "verified", "value": False},
      "possibleIRD": False},
     {"additionalDepreciationAtDeath": 0,
      "heirHoldingPeriodBegins": "2026-03-15",
      "decedentDepreciationCarriesOver": False,
      "decedentDepreciationRecapturedByHeir": False,
      "flags": ["FLAG_INHERITED_RENTAL_DEPRECIATION_RESTART"],
      "requiredFlagText": "Inherited rental property. Depreciation restarts on the adjusted basis as of the date of death; the decedent's prior depreciation generally does not carry over. Only the heir's own post-inheritance depreciation is relevant on a later sale.",
      "mustNotSay": "Depreciation history may affect sale treatment",
      "exceptionsToFlagSeparately": ["property is IRD", "IRC 1014(b)(9) - heir depreciated the property before the death"]},
     [R1250],
     "Reg. 1.1250-3(b): on a transfer at death the additional depreciation is ZERO and the "
     "holding period begins the day after death. The source document's suggested wording implies "
     "the decedent's depreciation history matters to the heir. It generally does not. Two "
     "exceptions get their own flags.")

emit("INH-16", "Cross-reference — the same distribution in two sections",
     "The inheritance module holding its own distribution totals.",
     {"inheritanceRecord": {"assetType": "inherited_traditional_ira", "accountId": "ACCT-INH-1",
                            "dateOfDeath": "2026-03-14"},
      "ledgerEntries": [{"id": "L-1", "accountId": "ACCT-INH-1", "kind": "distribution",
                         "tags": [], "amount": 45000, "date": "2026-11-20"}]},
     {"inheritanceSectionDistributionTotal": 45000,
      "page4DistributionTotal": 45000,
      "householdTotalDistributions": 45000,
      "sumOfSectionsIfNaivelyAdded": 90000,
      "crossReferenceRequired": True,
      "crossReferenceText": "Includes $45,000 of inherited IRA distributions, also shown in the Inheritance & Beneficiary Activity section.",
      "inheritanceModuleHoldsOwnTotals": False},
     ["cpa-packet/CPA-PACKET-SPEC.md section 4 and section 7"],
     "READ THIS ONE BY HAND. An inherited IRA is BOTH an inheritance record AND a ledger "
     "account. The distribution lives in the ledger and nowhere else; both sections query it. "
     "If the household total comes back $90,000 the module kept its own copy. Same failure "
     "mode as the QCD double-count, same fix.")

with open(os.path.join(ROOT, "INDEX.json"), "w") as f:
    json.dump(INDEX, f, indent=2)

print(f"emitted {len(INDEX)} inheritance fixtures")
for r in INDEX:
    print(f"  {r['id']}: {r['title']}")
    print(f"      catches: {r['catches']}")
