import json, os, sys
from decimal import Decimal as D
sys.path.insert(0, os.path.dirname(__file__))
from oracle import compute_year, irmaa_annual, rmd_age, rmd_amount, FPL_2025, senior_deduction

ROOT = os.path.join(os.path.dirname(__file__), "..", "fixtures")

def ser(o):
    if isinstance(o, D):
        s = str(o)
        return float(s) if "." in s else int(s)
    if isinstance(o, dict):
        return {k: ser(v) for k, v in o.items()}
    if isinstance(o, list):
        return [ser(v) for v in o]
    return o

INDEX = []

def emit(folder, fid, title, tests, inputs, expected, notes=None, tolerance=0.01, authority=None):
    doc = {
        "id": fid,
        "title": title,
        "tax_year": 2026,
        "law_mode": "current_law",
        "tests": tests,
        "authority": authority or [],
        "input": ser(inputs),
        "expected": ser(expected),
        "tolerance_dollars": tolerance,
        "notes": notes or "",
        "oracle": "hand-traced IRS worksheet; see tools/oracle.py — NOT generated by src/engine",
    }
    path = os.path.join(ROOT, folder, fid + ".json")
    with open(path, "w") as f:
        json.dump(doc, f, indent=2)
    INDEX.append({"id": fid, "folder": folder, "title": title, "tests": tests})
    return doc

def fed(**kw):
    r = compute_year(**kw)
    return {k: v for k, v in r.items() if not k.startswith("_")}, r

def keyexp(r):
    return {
        "provisional_income": r["step2_provisional_income"],
        "taxable_social_security": r["step3_taxable_social_security"],
        "agi": r["step4_agi"],
        "magi": r["step5_magi"],
        "senior_bonus_deduction": r["step6_deductions"]["senior_bonus_deduction"],
        "total_deductions": r["step6_deductions"]["total"],
        "taxable_income": r["step7_taxable_income"],
        "ordinary_taxable_income": r["step8_ordinary_taxable_income"],
        "preferential_taxed_at_0": r["step8_taxed_at_0"],
        "preferential_taxed_at_15": r["step8_taxed_at_15"],
        "preferential_taxed_at_20": r["step8_taxed_at_20"],
        "regular_tax": r["step8_regular_tax"],
        "niit": r["step9_niit"],
        "total_federal_tax": r["total_federal_tax"],
    }

RP = "Rev. Proc. 2025-32 (2026 inflation adjustments)"
SSW = "Form 1040 instructions, Social Security Benefits Worksheet (IRC 86)"
QDW = "Form 1040 instructions, Qualified Dividends and Capital Gain Tax Worksheet"
S1A = "Schedule 1-A (Form 1040), Part V, lines 33-36b"
F8960 = "Form 8960 (IRC 1411)"
F8962 = "Form 8962 instructions (IRC 36B)"

# ===========================================================================
# federal/ — bracket + standard deduction mechanics, no SS, no preferential
# ===========================================================================

i = dict(status="single", ages=[45], wages=60000)
r_, r = fed(**i); emit("federal", "FED-01", "Single, 45, wages only",
    ["standard_deduction", "ordinary_brackets"], i, keyexp(r), authority=[RP],
    notes="Baseline sanity check. No age add-on, no senior deduction.")

i = dict(status="mfj", ages=[45, 44], wages=150000)
r_, r = fed(**i); emit("federal", "FED-02", "MFJ, both under 65, wages only",
    ["standard_deduction", "ordinary_brackets"], i, keyexp(r), authority=[RP])

i = dict(status="mfj", ages=[67, 66], ira_distributions=80000)
r_, r = fed(**i); emit("federal", "FED-03", "MFJ, both 65+, IRA distribution only",
    ["age_65_additional_standard_deduction", "senior_bonus_deduction", "ordinary_brackets"], i,
    keyexp(r), authority=[RP, S1A],
    notes="Both spouses get the $1,650 age add-on AND a $6,000 senior deduction each.")

i = dict(status="mfj", ages=[67, 62], ira_distributions=80000)
r_, r = fed(**i); emit("federal", "FED-04", "MFJ, ONE spouse 65+, IRA distribution only",
    ["age_65_additional_standard_deduction", "senior_bonus_deduction"], i, keyexp(r),
    authority=[RP, S1A],
    notes="Exactly one $1,650 add-on and exactly one $6,000 senior deduction. "
          "Compare against FED-03: difference must be exactly $7,650 of deductions.")

i = dict(status="single", ages=[45], wages=66500)
r_, r = fed(**i); emit("federal", "FED-05", "Single, taxable income exactly at top of 12% bracket",
    ["bracket_boundary"], i, keyexp(r), authority=[RP],
    notes="Taxable income must equal exactly $50,400.")

i = dict(status="single", ages=[45], wages=66501)
r_, r = fed(**i); emit("federal", "FED-06", "Single, one dollar into the 22% bracket",
    ["bracket_boundary"], i, keyexp(r), authority=[RP],
    notes="Tax must exceed FED-05 by exactly $0.22.")

# ===========================================================================
# social-security/ — IRC 86 tiers and the torpedo
# ===========================================================================

i = dict(status="mfj", ages=[68, 67], gross_ss=48000, ira_distributions=6000)
r_, r = fed(**i); emit("social-security", "SS-01", "MFJ, provisional income below $32,000 — zero taxable SS",
    ["ss_tier_0"], i, keyexp(r), authority=[SSW],
    notes="Provisional income $30,000. Worksheet line 9 <= 0, so taxable SS is zero. "
          "The engine must NOT apply a flat 85% assumption.")

i = dict(status="mfj", ages=[68, 67], gross_ss=48000, ira_distributions=18000)
r_, r = fed(**i); emit("social-security", "SS-02", "MFJ, provisional income inside the 50% band",
    ["ss_tier_50"], i, keyexp(r), authority=[SSW])

i = dict(status="mfj", ages=[68, 67], gross_ss=48000, ira_distributions=20000)
r_, r = fed(**i); emit("social-security", "SS-03", "MFJ, provisional income exactly $44,000",
    ["ss_tier_boundary"], i, keyexp(r), authority=[SSW],
    notes="Boundary fixture. Provisional income must be exactly $44,000.")

i = dict(status="mfj", ages=[68, 67], gross_ss=48000, ira_distributions=20001)
r_, r = fed(**i); emit("social-security", "SS-04", "MFJ, one dollar past $44,000",
    ["ss_tier_boundary", "ss_tier_85"], i, keyexp(r), authority=[SSW],
    notes="Taxable SS must rise by exactly $0.85 versus SS-03.")

i = dict(status="mfj", ages=[68, 67], gross_ss=48000, ira_distributions=140000)
r_, r = fed(**i); emit("social-security", "SS-05", "MFJ, 85% ceiling fully reached",
    ["ss_tier_85", "ss_ceiling"], i, keyexp(r), authority=[SSW],
    notes="Taxable SS must equal exactly 85% of gross ($40,800) and must not exceed it.")

i = dict(status="single", ages=[70], gross_ss=30000, ira_distributions=14000)
r_, r = fed(**i); emit("social-security", "SS-06", "Single, 50% band",
    ["ss_tier_50", "filing_status_single"], i, keyexp(r), authority=[SSW])

i = dict(status="mfj", ages=[68, 67], gross_ss=48000, ira_distributions=14000, tax_exempt_interest=8000)
r_, r = fed(**i); emit("social-security", "SS-07", "MFJ, municipal bond interest enters provisional income",
    ["ss_tax_exempt_interest"], i, keyexp(r), authority=[SSW],
    notes="Tax-exempt interest is EXCLUDED from AGI but INCLUDED in provisional income "
          "(worksheet line 4). A common engine bug is omitting it here.")

def pair(folder, fid, title, base, delta_conversion, tests, authority, notes_a="", notes_b=""):
    """Emit a baseline/conversion pair and record the effective marginal rate between them.
    Pairs are how the engine's MARGINAL behaviour gets tested, not just its level."""
    r_, rb = fed(**base)
    emit(folder, fid + "a", title + " — baseline", tests, base, keyexp(rb),
         authority=authority, notes=notes_a)
    conv = dict(base); conv["roth_conversion"] = base.get("roth_conversion", 0) + delta_conversion
    r_, rc = fed(**conv)
    e = keyexp(rc)
    e["_pair_delta"] = {
        "baseline_fixture": fid + "a",
        "delta_conversion": D(delta_conversion),
        "delta_taxable_social_security": rc["step3_taxable_social_security"] - rb["step3_taxable_social_security"],
        "delta_taxable_income": rc["step7_taxable_income"] - rb["step7_taxable_income"],
        "delta_senior_bonus_deduction": rc["step6_deductions"]["senior_bonus_deduction"] - rb["step6_deductions"]["senior_bonus_deduction"],
        "delta_niit": rc["step9_niit"] - rb["step9_niit"],
        "delta_total_federal_tax": rc["total_federal_tax"] - rb["total_federal_tax"],
        "effective_marginal_rate_on_conversion":
            ((rc["total_federal_tax"] - rb["total_federal_tax"]) / D(delta_conversion)).quantize(D("0.000001")),
    }
    emit(folder, fid + "b", title + f" — +${delta_conversion:,} conversion", tests, conv, e,
         authority=authority, notes=notes_b)

# SS-08: torpedo pair. Provisional income must sit INSIDE the 85% phase-in band
# ($44,000 to ~$96,941 for $60,000 of benefits), otherwise the torpedo is already spent.
pair("social-security", "SS-08", "Social Security torpedo, inside the phase-in band",
     dict(status="mfj", ages=[68, 67], gross_ss=60000, ira_distributions=50000), 10000,
     ["ss_torpedo", "marginal_rate_pair"], [SSW, RP],
     notes_a="Provisional income $80,000 — inside the 85% phase-in band.",
     notes_b="Each conversion dollar drags $0.85 of benefits into taxable income, so taxable "
             "income rises by $18,500 on a $10,000 conversion. Nominal bracket 12%; effective "
             "marginal rate 22.2%. If your engine reports 12% here, the torpedo is not modeled.")

# SS-09: torpedo already fully spent — the control case
pair("social-security", "SS-09", "Social Security torpedo already spent (85% ceiling reached)",
     dict(status="mfj", ages=[68, 67], gross_ss=60000, ira_distributions=70000), 10000,
     ["ss_torpedo", "ss_ceiling", "marginal_rate_pair"], [SSW, RP],
     notes_a="Provisional income $100,000 — past the ceiling, taxable SS already $51,000 (85%).",
     notes_b="CONTROL CASE. Torpedo is fully spent, so the effective marginal rate must equal "
             "the clean nominal bracket. A tool that reports an inflated rate here is "
             "double-counting.")

# ===========================================================================
# senior-deduction/ — the reviewer's explicitly requested boundary set
# ===========================================================================

def sd_case(fid, magi_target, ages, status, title, notes=""):
    # drive MAGI with a pure IRA distribution so MAGI == AGI == the target
    i = dict(status=status, ages=ages, ira_distributions=magi_target)
    r_, r = fed(**i)
    e = keyexp(r)
    e["_schedule_1a_trace"] = {k: v for k, v in r["step6_deductions"]["_schedule_1a"].items()}
    return emit("senior-deduction", fid, title, ["senior_bonus_deduction", "phaseout_boundary"],
                i, e, authority=[S1A], notes=notes)

sd_case("SD-01", 149999, [67, 66], "mfj", "MFJ both 65+, MAGI $149,999 — full $12,000",
        "One dollar below the phaseout start. Deduction must be exactly $12,000.")
sd_case("SD-02", 150000, [67, 66], "mfj", "MFJ both 65+, MAGI exactly $150,000 — full $12,000",
        "At the threshold the excess is zero, so the deduction is still full.")
sd_case("SD-03", 150001, [67, 66], "mfj", "MFJ both 65+, MAGI $150,001 — first dollar of phaseout",
        "CRITICAL. Reduction is 6% PER PERSON (IRC 151(d)(5)) = $0.12 total, not $0.06. "
        "Expected deduction $11,999.88. If your engine returns $11,999.94 you have the classic bug. "
        "NOTE: rounding policy on Schedule 1-A is a RULE DECISION - see spec section 6.")
sd_case("SD-04", 200000, [67, 66], "mfj", "MFJ both 65+, mid-phaseout at MAGI $200,000",
        "Excess $50,000 x 6% = $3,000 reduction per person. $3,000 remains each, $6,000 total.")
sd_case("SD-05", 249999, [67, 66], "mfj", "MFJ both 65+, MAGI $249,999 — nearly gone")
sd_case("SD-06", 250000, [67, 66], "mfj", "MFJ both 65+, MAGI $250,000 — exactly zero",
        "Full phaseout point for MFJ with both spouses qualifying.")
sd_case("SD-07", 300000, [67, 66], "mfj", "MFJ both 65+, MAGI $300,000 — floored at zero",
        "Must not go negative.")
sd_case("SD-08", 200000, [67, 62], "mfj", "MFJ, ONE spouse 65+, MAGI $200,000",
        "Only line 36a is populated. Deduction = $3,000, exactly half of SD-04.")
sd_case("SD-09", 75001, [67], "single", "Single 65+, MAGI $75,001 — first dollar of phaseout",
        "Single rate is 6% total. Expected $5,999.94.")
sd_case("SD-10", 175000, [67], "single", "Single 65+, MAGI $175,000 — exactly zero")
sd_case("SD-11", 120000, [62, 60], "mfj", "MFJ, NEITHER spouse 65+ — no senior deduction",
        "Deduction must be $0 regardless of MAGI. Also no $1,650 age add-on.")

# SD-12: the marginal consequence of the phaseout — the reviewer's priority fixture
pair("senior-deduction", "SD-12", "Senior deduction phaseout surtax band (MFJ, both 65+)",
     dict(status="mfj", ages=[67, 66], ira_distributions=190000), 10000,
     ["senior_bonus_deduction", "phaseout_marginal_rate", "marginal_rate_pair"], [S1A, RP],
     notes_a="MAGI $190,000 — inside the $150,000-$250,000 phaseout band.",
     notes_b="THE fixture that catches the 6%-vs-12% bug at the level that matters. "
             "Taxable income rises by $11,200 on a $10,000 conversion (1.12x), so the 22% "
             "bracket costs 24.64%. If your engine produces 23.32% you applied 6% instead "
             "of 12%. If it produces 22.00% you did not model the phaseout at all.")

# SD-13: senior deduction reduces taxable income but NOT AGI, so it does not move any MAGI
i = dict(status="mfj", ages=[67, 66], ira_distributions=160000)
r_, r = fed(**i)
e = keyexp(r)
e["_invariant"] = {"magi_irmaa_equals_agi": True, "senior_deduction_reduces_agi": False}
emit("senior-deduction", "SD-13", "Senior deduction does not reduce AGI or any MAGI",
     ["senior_bonus_deduction", "magi_isolation"], i, e, authority=[S1A],
     notes="The senior deduction is taken BELOW the line. It reduces taxable income only. "
           "It must not reduce AGI, and therefore must not reduce IRMAA MAGI, NIIT MAGI or "
           "ACA MAGI. Engines that treat it as an above-the-line adjustment will understate "
           "IRMAA and overstate ACA eligibility.")

# ===========================================================================
# capital-gains/ — stacking and NIIT
# ===========================================================================

i = dict(status="mfj", ages=[70, 69], ira_distributions=30000, qualified_dividends=12000, net_ltcg=28000)
r_, r = fed(**i); emit("capital-gains", "CG-01", "MFJ, all preferential income in the 0% bracket",
    ["qdcg_stacking", "ltcg_0_rate"], i, keyexp(r), authority=[QDW],
    notes="Regular tax must equal the ordinary-income tax alone; preferential tax is zero.")

i = dict(status="mfj", ages=[70, 69], ira_distributions=120000, qualified_dividends=12000, net_ltcg=28000)
r_, r = fed(**i); emit("capital-gains", "CG-02", "MFJ, preferential income straddles 0% / 15%",
    ["qdcg_stacking", "ltcg_straddle"], i, keyexp(r), authority=[QDW],
    notes="THE canonical stacking test. Ordinary income fills the bracket space first; "
          "preferential income stacks on top. Computing ordinary tax and preferential tax "
          "independently and adding them gives the wrong answer here.")

i = dict(status="mfj", ages=[70, 69], ira_distributions=260000, qualified_dividends=12000, net_ltcg=28000)
r_, r = fed(**i); emit("capital-gains", "CG-03", "MFJ, all preferential income at 15%",
    ["qdcg_stacking", "ltcg_15_rate", "niit"], i, keyexp(r), authority=[QDW, F8960])

i = dict(status="mfj", ages=[70, 69], ira_distributions=500000, qualified_dividends=20000, net_ltcg=200000)
r_, r = fed(**i); emit("capital-gains", "CG-04", "MFJ, preferential income reaching the 20% rate",
    ["qdcg_stacking", "ltcg_20_rate", "niit"], i, keyexp(r), authority=[QDW, F8960])

i = dict(status="mfj", ages=[70, 69], ira_distributions=190000, interest=20000, qualified_dividends=20000,
         ordinary_dividends=24000, net_ltcg=30000)
r_, r = fed(**i); emit("capital-gains", "CG-05", "MFJ, NIIT applies on the lesser of NII or MAGI excess",
    ["niit"], i, keyexp(r), authority=[F8960],
    notes="NIIT base is min(net investment income, MAGI - $250,000). Verify the engine uses "
          "the LESSER, and that the Roth conversion itself is NOT counted as net investment income.")

i = dict(status="mfj", ages=[70, 69], ira_distributions=180000, interest=20000,
         qualified_dividends=20000, ordinary_dividends=20000, net_ltcg=30000)
r_, r = fed(**i); emit("capital-gains", "CG-06", "MFJ, MAGI at the NIIT threshold — zero NIIT",
    ["niit", "niit_boundary"], i, keyexp(r), authority=[F8960],
    notes="MAGI must land at exactly $250,000; NIIT must be exactly $0.")

# conversion does not itself create NII, but it exposes existing NII to NIIT
pair("capital-gains", "CG-07", "Conversion drags existing investment income into NIIT",
     dict(status="mfj", ages=[70, 69], ira_distributions=120000, interest=15000,
          qualified_dividends=25000, ordinary_dividends=25000, net_ltcg=40000), 80000,
     ["niit", "marginal_rate_pair"], [F8960],
     notes_a="MAGI below the $250,000 NIIT threshold. NIIT is zero.",
     notes_b="The conversion is NOT net investment income, but it raises MAGI and therefore "
             "exposes previously untaxed investment income to the 3.8% tax. Master Spec "
             "section 9. The engine must not include the conversion itself in the NII base.")

# CG-08: the compound case — torpedo AND capital-gain stacking at once
pair("capital-gains", "CG-08", "Triple compound: SS torpedo + senior phaseout + LTCG stacking",
     dict(status="mfj", ages=[68, 67], gross_ss=120000, ira_distributions=40000,
          qualified_dividends=15000, net_ltcg=30000), 10000,
     ["ss_torpedo", "senior_bonus_deduction", "qdcg_stacking", "compound_marginal_rate",
      "marginal_rate_pair"], [SSW, QDW, S1A],
     notes_a="Deliberately tangled and deliberately realistic. Provisional income sits inside "
             "the 85% phase-in band, MAGI sits inside the senior-deduction phaseout band, and "
             "preferential income straddles the 0%/15% capital-gain boundary — all at once.",
     notes_b="THE HARDEST FIXTURE IN THE SET. One conversion dollar simultaneously: (a) is "
             "taxed at the ordinary rate, (b) drags $0.85 of Social Security into taxable "
             "income, (c) destroys $0.12 of senior deduction, and (d) pushes preferential "
             "income from 0% to 15%. Taxable income rises by more than 2x the conversion. "
             "If the engine passes every other fixture but fails this one, the individual "
             "provisions are right and the ORDER OF OPERATIONS is wrong.")

# ===========================================================================
# aca/ — the 400% FPL cliff  (2026 coverage uses 2025 HHS guidelines)
# ===========================================================================

def aca_case(fid, magi, household_size, title, notes=""):
    fpl400 = FPL_2025[household_size] * D("4")
    eligible = D(magi) <= fpl400
    return emit("aca", fid, title, ["aca_400_fpl_cliff"],
        {"aca_magi": magi, "household_size": household_size, "coverage_year": 2026,
         "region": "48_contiguous_states_and_dc"},
        {"fpl_100_percent": FPL_2025[household_size], "fpl_400_percent": fpl400,
         "fpl_percentage": (D(magi) / FPL_2025[household_size] * 100).quantize(D("0.0001")),
         "premium_tax_credit_eligible": eligible,
         "credit_multiplier": D(1) if eligible else D(0)},
        authority=[F8962, "HHS 2025 Poverty Guidelines (90 FR)"], notes=notes)

aca_case("ACA-01", 84599, 2, "Household of 2, MAGI $84,599 — one dollar under the cliff",
    "Credit is available. Compare with ACA-03.")
aca_case("ACA-02", 84600, 2, "Household of 2, MAGI exactly 400.00% FPL — still eligible",
    "At exactly 400% the credit survives.")
aca_case("ACA-03", 84601, 2, "Household of 2, MAGI $84,601 — CLIFF, credit drops to zero",
    "THE fixture. One dollar of extra conversion income destroys the entire credit. "
    "The engine must report the full dollar value of the lost credit as a modeled cost "
    "of the conversion, and must emit a discontinuity with rule id ACA_36B_400FPL_CLIFF.")
aca_case("ACA-04", 62600, 1, "Household of 1, MAGI exactly 400.00% FPL")
aca_case("ACA-05", 62601, 1, "Household of 1, one dollar over — cliff")

# ===========================================================================
# irmaa/ — 2026 premiums determined by 2024 MAGI
# ===========================================================================

def irmaa_case(fid, magi, status, n, title, notes=""):
    amt, meta = irmaa_annual(magi, status, n)
    return emit("irmaa", fid, title, ["irmaa_tier_lookup"],
        {"magi_irmaa": magi, "filing_status": status, "medicare_enrollees": n,
         "premium_year": 2026, "magi_source_tax_year": 2024},
        {"annual_household_surcharge_above_standard": amt, **meta},
        authority=["CMS 2026 Medicare Parts A & B Premiums and Deductibles"], notes=notes)

irmaa_case("IRMAA-01", 218000, "mfj", 2, "MFJ at exactly $218,000 — no surcharge",
    "At the threshold there is no surcharge. Surcharge begins ABOVE the listed amount.")
irmaa_case("IRMAA-02", 218001, "mfj", 2, "MFJ one dollar over — first tier",
    "One dollar of conversion income costs the household the full annual tier-1 surcharge. "
    "Discontinuity must carry rule id IRMAA_TIER_1. Note the 2-year lag: this is a 2028 cost "
    "caused by 2026 income.")
irmaa_case("IRMAA-03", 274001, "mfj", 2, "MFJ tier 2")
irmaa_case("IRMAA-04", 342001, "mfj", 2, "MFJ tier 3")
irmaa_case("IRMAA-05", 410001, "mfj", 2, "MFJ tier 4")
irmaa_case("IRMAA-06", 750001, "mfj", 2, "MFJ top tier")
irmaa_case("IRMAA-07", 109001, "single", 1, "Single tier 1 — surviving spouse case",
    "Same household income, one enrollee, single thresholds. This is the widow's-penalty "
    "interaction with Medicare.")
irmaa_case("IRMAA-08", 240000, "mfj", 1, "MFJ filing status, only one spouse enrolled in Medicare",
    "Surcharge applies per enrollee, not per household. A common engine bug is doubling it.")

# ===========================================================================
# rmd/
# ===========================================================================

for fid, by, exp_age, note in [
    ("RMD-01", 1952, 73, "SECURE 2.0: born 1951-1959 -> age 73."),
    ("RMD-02", 1959, 73, "The 1959 statutory drafting glitch. Treasury resolved to 73 in the "
                         "July 2024 final regulations. Document the citation in the rules file."),
    ("RMD-03", 1960, 75, "Born 1960 or later -> age 75. The current app hardcodes 73; this "
                         "fixture must fail before the Phase 1 fix and pass after."),
    ("RMD-04", 1971, 75, "Younger cohort."),
]:
    emit("rmd", fid, f"RMD applicable age, born {by}", ["rmd_applicable_age"],
         {"birth_year": by}, {"rmd_applicable_age": exp_age},
         authority=["SECURE 2.0 Act sec. 107", "T.D. 10001, 89 FR 58886 (July 19, 2024)"], notes=note)

for fid, bal, age in [("RMD-05", 1000000, 75), ("RMD-06", 500000, 73), ("RMD-07", 2400000, 80)]:
    amt, meta = rmd_amount(bal, age)
    emit("rmd", fid, f"Uniform Lifetime Table RMD, age {age}, balance ${bal:,}",
         ["rmd_uniform_lifetime_table"],
         {"prior_year_end_balance": bal, "age_at_year_end": age, "table": "uniform_lifetime"},
         {"rmd": amt, "distribution_period": meta["factor"]},
         authority=["Treas. Reg. 1.401(a)(9)-9(c)"],
         notes="Balance is the PRIOR December 31 value. Roth IRAs are excluded from lifetime RMDs.")

emit("rmd", "RMD-08", "Roth conversion cannot satisfy an RMD; RMD must come out first",
     ["rmd_ordering_rule"],
     {"birth_year": 1952, "tax_year": 2026, "prior_year_end_balance": 1000000,
      "attempted_roth_conversion": 100000},
     {"rmd_required_first": 40650.41, "amount_eligible_for_conversion": 959349.59,
      "conversion_of_rmd_amount_permitted": False,
      "excess_contribution": "rmd_amount_contributed_to_roth minus allowable_regular_roth_contribution",
      "excess_contribution_this_fixture": 40650.41,
      "allowable_regular_roth_contribution_this_fixture": 0},
     authority=["Treas. Reg. 1.408A-4, Q&A-6", "IRC 4973"],
     notes="First-dollars-out rule: the RMD is deemed distributed first and is NOT eligible "
           "for conversion. If contributed to a Roth anyway it is treated as a REGULAR "
           "contribution, and is an excess contribution (6% IRC 4973 excise) only to the "
           "extent it exceeds the allowable regular Roth contribution. Here the retiree has "
           "no compensation, so the allowance is $0 and the entire amount is excess. "
           "DO NOT hard-code 'always fully excess' - compute the allowance.")

with open(os.path.join(ROOT, "INDEX.json"), "w") as f:
    json.dump(INDEX, f, indent=2)

print(f"emitted {len(INDEX)} fixtures")
for row in INDEX:
    print(f"  {row['folder']}/{row['id']}: {row['title']}")
